### ISSUE TITLE
A bug in interface.py

### ISSUE THREAD

**Issue by YifengMa9** [FuxiVirtualHuman/AAAI22_ONE-SHOT_TALKING_FACE_GEN#2]
Line 74. there are extra space in keys. 
`pose = [pos_data[" pose_Rx"][i], pos_data[" pose_Ry"][i], pos_data[" pose_Rz"][i],pos_data[" pose_Tx"][i], pos_data[" pose_Ty"][i], pos_data[" pose_Tz"][i]]` 
should be 
`pose = [pos_data["pose_Rx"][i], pos_data["pose_Ry"][i], pos_data["pose_Rz"][i],pos_data["pose_Tx"][i], pos_data["pose_Ty"][i], pos_data["pose_Tz"][i]]` 

Thanks for your remarkable work. The performance is amazing.

**Comment by FuxiVirtualHuman** [comment]
> R

This is caused by the different versions of Openface and the different paltforms.

**Comment by yaleimeng** [comment]
windows版本的csv，列名前面有空格；Linux版本的csv文件，列名不包含空格。
项目代码是默认按前面带空格的形式，修改一下就可以了。

**Comment by YifengMa9** [comment]
Thanks

**Comment by rlgnswk** [comment]
Thanks for your recording!
