### ISSUE TITLE
Missed config.py file?

### ISSUE THREAD

**Issue by zhanghm1995** [FuxiVirtualHuman/AAAI22_ONE-SHOT_TALKING_FACE_GEN#3]
Hi, thanks for sharing this amazing work.

When I want to run the test_script.py, I got the error that there did not exist the config.py file, did you missed to upload it?

**Comment by yaleimeng** [comment]
代码中好几处用到，似乎确实漏掉了这个文件。自己建这个config又比较麻烦。
不过我通过修改代码中config里面的变量和命令行参数，强行让代码跑了起来。

**Comment by zhanghm1995** [comment]
OK，那我也修改下试试.

**Comment by FuxiVirtualHuman** [comment]
> Hi, thanks for sharing this amazing work.
> 
> When I want to run the test_script.py, I got the error that there did not exist the config.py file, did you missed to upload it?

Sorry for the missing.  Upload it already.

**Comment by zhanghm1995** [comment]
@FuxiVirtualHuman Thanks a lot!

**Comment by ABC0408** [comment]
> 代码中好几处用到，似乎确实漏掉了这个文件。自己建这个config又比较麻烦。 不过我通过修改代码中config里面的变量和命令行参数，强行让代码跑了起来。


你好，这个问题https://github.com/FuxiVirtualHuman/AAAI22-one-shot-talking-face/issues/6 你遇到了吗？音频的特征怎么提到41维的呢？你有跑出demo的效果吗？

**Comment by yaleimeng** [comment]
@ABC0408 
作者提供的demo是跑通了。但是项目既不能换人物，换声音都要联系作者，对中文支持也很差，早就放弃了。

**Comment by ABC0408** [comment]
> @ABC0408 作者提供的demo是跑通了。但是项目既不能换人物，换声音都要联系作者，对中文支持也很差，早就放弃了。

我用的图片，音频和音素，都是samples里面给的，效果也和demo里面的差太多了，不知道是不是我音频的特征没调好导致的，论文和代码里面都没说41维是怎么分配的。
![image](https://user-images.githubusercontent.com/20503529/182509053-e7d715ce-75df-4377-a648-1964e7bb50b1.png)


https://user-images.githubusercontent.com/20503529/182508830-ece645ca-541f-46cb-b49e-87e5fb04469f.mp4

。
