### ISSUE TITLE
Environment issue

### ISSUE THREAD

**Issue by JH-LEE-KR** [FuxiVirtualHuman/AAAI22_ONE-SHOT_TALKING_FACE_GEN#7]
Hi,

I am trying to do some experiments using your codes and there's some problem.

There is only an explanation of Openface setup on the windows environment in the README.
How can I use it in a ubuntu environment?

I look forward to hearing from you.

Best.
Jaeho Lee.

**Comment by arsyad-ah** [comment]
Hi @Lee-JH-KR,

I believe you can set it up in Ubuntu using this link - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

In `config.py`, path to openface should be `OPENFACE_POSE_EXTRACTOR_PATH = "<path to OpenFace repo>/build/bin/FeatureExtraction"`

**Comment by JH-LEE-KR** [comment]
Thanks for your reply!

I'll do what you've told you.

Thank you again.

Best.
Jaeho Lee.
